### Project Description

Calculating a person's medical insurance costs by considering certain factors that contribute to medical insurance costs. Estimation calculations of a person's medical insurance costs that affect the prediction, from datas such as age, sex, BMI, number of children, and if the person is smoking or not.

In [1]:
# Features that need to be consider when estimating medical insurance costs
age = 40
sex = 1               ## 0 for female, 1 for male
bmi = 25.5
num_of_children = 0
smoker = 1            ## 0 for a non-smoker, 1 for a smoker

In [2]:
# Creating the formula
insurance_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500

In [4]:
print("This person's insurance cost is " + str(insurance_cost) + " dollars.")

This person's insurance cost is 30807.0 dollars.


##### >> Looking at changing the age factor affecting to the insurance costs.

In [5]:
# Changing the age features value
age += 4

In [6]:
age

44

In [7]:
new_insurance_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500

In [8]:
print("This person's insurance cost is " + str(new_insurance_cost) + " dollars.")

This person's insurance cost is 31807.0 dollars.


In [9]:
change_in_insurance_cost = new_insurance_cost - insurance_cost

In [10]:
print("The change in cost of insurance after increasing the age by 4 years is " + str(change_in_insurance_cost) + 
      " dollars.")

The change in cost of insurance after increasing the age by 4 years is 1000.0 dollars.


As this person getting older, the medical insurance will cost more.

##### >> Looking at changing the BMI factor affecting to the insurance costs.

In [11]:
# set age feature to its original value
# change the bmi feature value
age = 40
bmi += 3.1

In [12]:
bmi

28.6

In [13]:
new_insurance_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500

In [14]:
print("This person's insurance cost is " + str(new_insurance_cost) + " dollars.")

This person's insurance cost is 31954.0 dollars.


In [15]:
change_in_insurance_cost = new_insurance_cost - insurance_cost

In [16]:
print("The change in estimated insurance cost after increasing BMI by 3.1 is " + str(change_in_insurance_cost) + 
      " dollars.")

The change in estimated insurance cost after increasing BMI by 3.1 is 1147.0 dollars.


Change in BMI factor affecting the medical insurance cost. As in this example the BMI values increasing, so does the medical insurance cost is. The insurance cost increasing by 1147.0 dollars.

##### >> Looking at the gender factor affecting the medical insurance costs.

In [17]:
# set the bmi feature to its orginal value
# changing the sex feature value
bmi = 25.5
sex = 0

In [18]:
new_insurance_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500

In [19]:
print("This person's insurance cost is " + str(new_insurance_cost) + " dollars.")

This person's insurance cost is 30935.0 dollars.


In [20]:
change_in_insurance_cost = new_insurance_cost - insurance_cost

In [21]:
print("The change in estimated insurance cost for being female instead of male is " + str(change_in_insurance_cost) + 
      " dollars.")

The change in estimated insurance cost for being female instead of male is 128.0 dollars.


The result by changing gender showed that men tend to have lower medical costs on average than women.

##### >> Looking at the smoking factor affecting the medical insurance costs.

In [23]:
# set the sex feature values to its original
# change the smoker value
sex = 1
smoker = 0

In [24]:
new_insurance_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500

In [25]:
print("This person's insurance cost is " + str(new_insurance_cost) + " dollars.")

This person's insurance cost is 6807.0 dollars.


In [26]:
change_in_insurance_cost = new_insurance_cost - insurance_cost

In [27]:
print("The change in estimated insurance cost for being female instead of male is " + str(change_in_insurance_cost) + 
      " dollars.")

The change in estimated insurance cost for being female instead of male is -24000.0 dollars.


If this person is not smoking resulting the insurance cost around 6807.0 dollars, way cheaper that if the person is smoking. As seen the change result is around 24000 dollars which will save lot of cost of medical insurance.

### Using function to Calculate the Medical Insurance Costs

In [2]:
def calculate_insurance_cost(name, age, sex, bmi, num_of_children, smoker):
    estimated_cost = 250*age - 128*sex + 370*bmi + 425*num_of_children + 24000*smoker - 12500
    print("The estimated insurance cost for " + name + " is "+ str(estimated_cost) + " dollars.")
    return estimated_cost

In [4]:
me_insurance_cost = calculate_insurance_cost(name= "me", age=32, sex=0, bmi=27, num_of_children=0, smoker=0)

The estimated insurance cost for me is 5490 dollars.
